[Bugfix:System] rsync .setup/data to worker machines (#13479)
### Why is this Change Important & Necessary?

Submitty software update/installation on worker machines was failing
because
the `.setup/data/configs/worker/` directory was not being copied from
the primary
machine to the worker machines.

This directory was added with this PR:
https://github.com/Submitty/Submitty/pull/12438

An rsync exclusion file was created and included the .setup/data
directory with this PR:
https://github.com/Submitty/Submitty/pull/8227

The worker fails here:
```
<SNIP>

python3 "${SUBMITTY_REPOSITORY}/.setup/generate_configs.py" ${COMMAND}
preserve list OrderedDict()
Traceback (most recent call last):
  File "/usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/generate_configs.py", line 62, in <module>
    for item in os.listdir(source):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/data/configs/worker'
preserve_files_restore
```

### What is the New Behavior?
Removing this directory from the exclusion solved the installation error
on worker machines.

Co-authored-by: Barb Cutler <Barb Cutler>