[Feature:RainbowGrades] Load and Save on Nightly Build (#11496)
### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were
made

### What is the current behavior?
<!-- List issue if it fixes/closes/implements one using the "Fixes
#<number>" or "Closes #<number>" syntax -->

`sbin/generate_grade_summaries.py` only generates Rainbow Grades
summaries, but it would be helpful to confirm the customization file can
be loaded and saved over the network before generating the most
up-to-date grade summaries, logging any errors along the way for
debugging purposes. Additionally, the only errors logged to STDERR are
noted as invalid arguments, but customization file errors could also be
thrown at runtime.

### What is the new behavior?

`sbin/generate_grade_summaries.py` now loads the Rainbow Grades
customization page response for a given course, saving its most
up-to-date configuration values before submitting the build process and
generating grade summaries. This update only applies to courses without
manual customization files. Errors are also now more specific in terms
of their causes, which can be helpful for system administrators. The
significance of this change is that if instructors have nightly builds
enabled (default true), then Rainbow Grades is automatically synced each
day, implying the Rainbow Grades Summary Page data for students is now
based on the given day instead of having to wait for instructors to
manually hit the build button on the configuration page.

### Other information?
<!-- Is this a breaking change? -->
<!-- How did you test -->

You can run the script as the `submitty_daemon` user, as shown below.
Once the script runs successfully, the Rainbow Grades Summary page
should catch any changes in assignment updates, such as new
student-visible assignments, updates to assignments, and updates in
grade reports.

`sbin/generate_grade_summaries.py`
```bash
$ sudo su submitty_daemon
$ python3 sbin/generate_grade_summaries.py f25 sample submitty_daemon
Successfully selected the manual customization for f25.sample
Successfully submitted the Rainbow Grades build process for f25.sample
Successfully completed the Rainbow Grades build process for f25.sample - {'status': 'success', 'data': 'Started build at 2025-07-02 13:12:33.696023\nPreviously configured Makefile detected\nGenerating grade summaries\nSuccessfully generated grade summaries for f25.sample\nPulling in grade summaries\nCompiling rainbow grades\nExporting to summary_html\nUpdating permissions\nDone'}
Successfully generated grade summaries for f25.sample
$ python3 sbin/generate_grade_summaries.py f25 sample submitty_daemon
Successfully saved Rainbow Grades GUI customization for f25.sample
Successfully selected the gui customization for f25.sample
Successfully submitted the Rainbow Grades build process for f25.sample
Successfully completed the Rainbow Grades build process for f25.sample - {'status': 'success', 'data': 'Started build at 2025-07-02 13:23:17.217548\nPreviously configured Makefile detected\nGenerating grade summaries\nSuccessfully generated grade summaries for f25.sample\nPulling in grade summaries\nCompiling rainbow grades\nExporting to summary_html\nUpdating permissions\nDone'}
Successfully generated grade summaries for f25.sample
$ python3 sbin/generate_grade_summaries.py f25 developement submitty_daemon
ERROR: Failed to save Rainbow Grades GUI customization for f25.developement - Failed to load course. Check course title and ensure it exists.
```

To compare the website and the script `customization.json` file
modifications, run the following command after building through either
method and compare the outputs, which should only differ in whitespace
and key ordering in the worst-case scenario.

```bash
root@ubuntu:/usr/local/submitty# cat /var/local/submitty/courses/f25/sample/rainbow_grades/customization.json
```

Additionally, the script should be run manually by an existing cron job,
which can be run through the following steps

```bash
root@ubuntu:/usr/local/submitty# sudo -u submitty_daemon python3 -u sbin/auto_rainbow_scheduler.py # This runs daily, which will lead to generate_grade_summaries.py to be called
root@ubuntu:/usr/local/submitty# ls /var/local/submitty/daemon_job_queue # Run until this directory is empty (represents the job queue)
```

NOTE: Updates may take a while to display as changes are processed on
the server within a queue. Please wait until all rainbow grade-related
queue items are resolved, which can be found in
`/var/local/submitty/daemon_job_queue`.

---------

Co-authored-by: Jeffrey Cordero <JeffreyCorderoNY@gmail.com>
Co-authored-by: Jeffrey Cordero <94331560+jeffrey-cordero@users.noreply.github.com>
Co-authored-by: Barb Cutler <bmcutler@users.noreply.github.com>