[Bugfix:Autograding] skip queue files with json load error (#11452)
### What is the current behavior?

We apparently have a race condition. If the autograding queue file is
partial/incomplete
the autograding scheduler will fail to load the json object. This error
is logged to

`/var/local/submitty/logs/autograding_stack_traces/CURRENTDATE.txt`

```
== Traceback (most recent call last):
==   File "/usr/local/submitty/autograder/autograder/scheduler.py", line 48, in _try_load_queue_object
==     self._queue_obj = json.load(f)
==   File "/usr/lib/python3.10/json/__init__.py", line 293, in load
==     return loads(fp.read(),
==   File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
==     return _default_decoder.decode(s)
==   File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
==     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
==   File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
==     obj, end = self.scan_once(s, idx)
== json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: SOMETHING
```

We do have a try/catch around the json load, however, a `None` object is
passed through and fails to be sorted:

```
Traceback (most recent call last):
  File "/usr/local/submitty/autograder/submitty_autograding_shipper.py", line 1845, in <module>
    monitoring_loop(config, processes)
  File "/usr/local/submitty/autograder/submitty_autograding_shipper.py", line 1764, in monitoring_loop
    sched.update_and_schedule()
  File "/usr/local/submitty/autograder/autograder/scheduler.py", line 175, in update_and_schedule
    self._assign_jobs(self._list_jobs())
  File "/usr/local/submitty/autograder/autograder/scheduler.py", line 201, in _assign_jobs
    jobs.sort(key=lambda j:
  File "/usr/local/submitty/autograder/autograder/scheduler.py", line 203, in <lambda>
    not ("vcs_checkout" in j.queue_obj and
TypeError: argument of type 'NoneType' is not iterable
```

which crashes the autograding shipper scheduler -- which requires a
system to restart.

This error can be reproduced by putting many jobs into the autograding
queue
https://submitty.org/instructor/autograding/batch_regrade

Then manually editing one of those queue files -- the queue files are
stored here:
/var/local/submitty/logs/autograding_stack_traces/to_be_graded_queue/*
to be broken json.

And you will see all autograding has stopped.

Information about testing & debugging the shipper & worker are here:

https://submitty.org/developer/development_instructions/automated_grading

### What is the new behavior?

Now the `None` job will be pulled out of the list before sorting, so the
scheduler will not crash.

Note that the original race condition with the incompletely written file
will resolve before the next loop.
And thus all jobs will be graded. No sysadmin restart will be necessary.

### Other information?

This JSONDecoderError will still appear in the log whenever this race
condition happens.

We should revisit the race condition in a future PR. Perhaps the
directory should be locked before writing or reading queue files.

Co-authored-by: Barb Cutler <Barb Cutler>