[Testing:System] Add Vue Type Checks for Build Process (#11868)
### Why is this Change Important & Necessary?
<!-- Include any GitHub issue that is fixed/closed using "Fixes
#<number>" or "Closes #<number>" syntax.
Alternately write "Partially addresses #<number>" or "Related to
#<number>" as appropriate. -->

The build process for the application front-end may be successful with
existing TypeScript errors, where there are many existing errors in
`.ts` and `.vue` files due to missing type imports and invalid compiler
configurations.

```bash
 site git:(add-type-checking) ✗ npm run build

> build
> tsc -p . && node .build.js && vite build vue

vite v7.0.3 building for production...
✓ 34 modules transformed.
../public/mjs/vue/submitty-vue.css      1.36 kB │ gzip: 0.54 kB
../public/mjs/vue/submitty-vue.umd.js  21.53 kB │ gzip: 6.45 kB
✓ built in 182ms
➜  site git:(add-type-checking) ✗ npm run type-check                

 site git:(add-type-checking) ✗ npm run build

> build
> tsc -p . && vue-tsc --noEmit && node .build.js && vite build vue

vue/src/components/popup.vue:6:10 - error TS2552: Cannot find name 'stringd'. Did you mean 'string'?

6     id?: stringd;
           ~~~~~~~


Found 1 error in vue/src/components/popup.vue:6
```

### What is the New Behavior?
<!-- Include before & after screenshots/videos if the user interface has
changed. -->

This builds on #11835, as I realized we don't use `vue-tsc`, but we
still make Dependabot updates regularly, so the library is now used for
dedicated type checks during the build process. This will also increase
the velocity of `@types/x`-related dependency update reviews, as they
typically lack dedicated change logs, where this would help find any
TypeScript errors caused by a dependency update.

`@types/node-fetch` was also added to our dependency list due to the
following error.

```bash
➜  site git:(add-type-checking) ✗ npm run build

> build
> tsc -p . && vue-tsc --noEmit && node .build.js && vite build vue

vue/src/components/popup.vue:6:10 - error TS2552: Cannot find name 'stringd'. Did you mean 'string'?

6     id?: stringd;
           ~~~~~~~


Found 1 error in vue/src/components/popup.vue:6
```


### What steps should a reviewer take to reproduce or test the bug or
new feature?

1. Add a TypeScript error to a `.vue` file
2. Run `npm run build`
3. Notice errors

### Automated Testing & Documentation
<!-- Is this feature sufficiently tested by unit tests and end-to-end
tests?
If this PR does not add/update the necessary automated tests, write a
new GitHub issue and link it below.
Is this feature sufficiently documented on submitty.org?
Link related PRs or new GitHub issue to update documentation. -->

N/A

### Other information
<!-- Is this a breaking change?  
Does this PR include migrations to update existing installations?  
Are there security concerns with this PR? -->

N/A

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Alex Lavallee <alex@lavallee.one>